services:
  db:
    image: postgres
    restart: always

    volumes:
      - db-data:/var/lib/postgres/data

    environment:
      - POSTGRES_DB=db_food_waste
      - POSTGRES_USER=appv01
      - POSTGRES_PASSWORD=yakuza_1234

    expose:
      - 5432

volumes:
    db-data: