services:
  db:
    image: postgres:15.12-alpine
    restart: always

    volumes:
      - db-data:/var/lib/postgres/data

    environment:
      - POSTGRES_DB=db_food_waste
      - POSTGRES_USER=appv01
      - POSTGRES_PASSWORD=yakuza_1234

    ports:
      - "5432:5432"

volumes:
    db-data: