services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: food_waste_app

    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/${DATASOURCE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    container_name: db_food_waste
    volumes:
      - db-data:/var/lib/postgres/data

    environment:
      - POSTGRES_DB=${DATASOURCE_DB_NAME}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}

    ports:
      - "5432:5432"

volumes:
    db-data: